CREATE TABLE users (
  id CHAR(36) PRIMARY KEY,               -- matches Auth userId
  email VARCHAR(255) UNIQUE NOT NULL,
  full_name VARCHAR(255),
  phone_no VARCHAR(64),
  kyc_level VARCHAR(32) DEFAULT 'BASIC',  -- BASIC, VERIFIED, REJECTED
  status VARCHAR(32) DEFAULT 'ACTIVE',    -- ACTIVE, SUSPENDED
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
